rudderlabs/profiles-pycorelib

setup.py, src/profiles-pycorelib/sample_model.py
> Add a sample and update existing model
> Fix [#1]()
=> chore: add sample and update model

src/profiles-pycorelib/sample_model.py
> Ignore the sample model, for v0.10.4
> Fix [#1]()
=> fix: ignore sample model

src/profiles-pycorelib/common_col_union.py
> Revert consolidated de_ref change
> Fix [#1]()
=> revert: de_ref changes

setup.py
=> chore: update profiles-rudderstack

setup.py, src/profiles-pycorelib/common_col_union.py, src/profiles-pycorelib/sample_model.py
> Update pynative models for v0.11.0
> Fix [#1]()
=> chore: update core lib models

setup.py
> Relax to version check from ==0.10.5 to >=0.10.5
> Fix [#1]()
=> chore: relax version bound check

setup.py
> Add support for `profiles-rudderstack` 0.10.7
> Fix [#1]()
=> chore: update ver for profiles-ruddestack 0.10.7

Makefile
> Tag created 0.11.0rc3 (should be) v0.11.0rc3
> Fix [#1]()
=> fix: make release tag missing v

.github/workflows/publish.yaml
GitHub action for publishing `profiles-pycorelib` to pypi
=> chore: pypi publish action

setup.py, src/profiles-pycorelib/attribution_model.py
> updated the heatmap generated for markov model transition probabilities into an interactive figure as .html file. Ticket [Link](https://linear.app/rudderstack/issue/PRML-567/update-attribution-output-heatmap-image).
> Fix [#1]()
=> generating interactive figures for attribution

.github/workflows/release.yaml
Pushing version bump commit to the source branch during a release
=> chore: push version bump during release to source branch

setup.py, src/profiles-pycorelib/attribution_model.py
> the converge method was using numpy functions. This is very inefficient at large scale. We created a branch using torch to resolve this. But this similar functionality can be achieved through scipy, as scipy is a lot more generic than torch. Ticket [Link](https://linear.app/rudderstack/issue/PRML-648/move-attribution-model-to-scipylinalg).
> Fix [#1]()
=> implementing matmul with scipy

src/profiles-pycorelib/attribution_model.py
> Making flags other than "entity" and "touchpoint_vars" optional. Ticket [link](https://linear.app/rudderstack/issue/PRML-620/make-lookback-period-and-conversion-entity-var-optional).
> Fix [#1]()
=> making flags optional

version.py
=> chore: sync release v0.14.0

.github/workflows/publish.yaml
=> chore: update publish.yaml

version.py
sync back for 0.15.0
> Fix [#1]()
=> chore: sync back 0.15.0 to main

version.py
> Sync Back for 0.16.0
> Fix [#1]()
=> chore: release sync back for 0.16.x

src/profiles-pycorelib/common_col_union.py, src/profiles-pycorelib/sample_model.py
> Update `edge_type` to `dependency`
[PRO-3234: PyNative deRefOptions coupling](https://linear.app/rudderstack/issue/PRO-3234/pynative-derefoptions-coupling)
> Fix [#1]()
=> fix: update kwargs for DeRef

src/profiles-pycorelib/common_col_union.py, src/profiles-pycorelib/sample_model.py
Fixed issues coming after the merge of simplified material wh names pr in wht
> Fix [#1]()
=> fix: issues related to IWhObject

version.py
=> chore: sync release 0.18.0

src/profiles-pycorelib/attribution_model.py
=> correcting zero devision error

.github/workflows/publish.yaml, version.py
sync release 0.22.0 
> Fix [#1]()
=> chore: sync release 0.22.0 

version.py
=> chore: sync release 0.23
